fail_fast: true

repos:
  - repo: local
    hooks:
      - id: black
        rev: 23.3.0
        args: [--skip-string-normalization, app, tests]
    
  - repo: local
    hooks:
      - id: pylint
        rev: 2.17.3
        name: pylint
        entry: pylint
        language: system
        types: [python]
        require_serial: true

  - repo: local
    hooks:
      - id: mypy
        rev: 1.2.0
        args: [app]
