"""image_original_filename

Revision ID: 6de4c1bded16
Revises: d9a83e297270
Create Date: 2023-04-27 12:02:14.914031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6de4c1bded16'
down_revision = 'd9a83e297270'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('original_filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'original_filename')
    # ### end Alembic commands ###
