"""recipe_and_step_image

Revision ID: d9a83e297270
Revises: 22d7c5661546
Create Date: 2023-04-27 00:59:05.693082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9a83e297270'
down_revision = '22d7c5661546'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('image_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'recipe', 'image', ['image_id'], ['id'], ondelete='RESTRICT')
    op.add_column('step', sa.Column('image_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'step', 'image', ['image_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'step', type_='foreignkey')
    op.drop_column('step', 'image_id')
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.drop_column('recipe', 'image_id')
    # ### end Alembic commands ###
