"""step_duration

Revision ID: db328dd91c23
Revises: fe4da3bed938
Create Date: 2023-04-26 15:17:13.601945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db328dd91c23'
down_revision = 'fe4da3bed938'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('step', sa.Column('duration', sa.Interval(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('step', 'duration')
    # ### end Alembic commands ###
